[tool.poetry]
name = "post-suffler-test"
version = "0.1.0"
description = ""
authors = ["davidgh86 <david_gh86@hotmail.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
